### ISSUE TITLE
Error while importing eml_parser

### ISSUE THREAD

**Issue by ramesh-chowdeshetty** [GOVCERT-LU/eml_parser#11]
Hi,

I am using python3, but i am unable to import eml_parser,

error

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rameshchowdeshetty/venv/lib/python3.4/site-packages/eml_parser/__init__.py", line 8, in <module>
    from . import eml_parser
  File "/Users/rameshchowdeshetty/venv/lib/python3.4/site-packages/eml_parser/eml_parser.py", line 59, in <module>
    import magic
  File "/Users/rameshchowdeshetty/venv/lib/python3.4/site-packages/magic.py", line 61, in <module>
    _open = _libraries['magic'].magic_open
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/ctypes/__init__.py", line 364, in __getattr__
    func = self.__getitem__(name)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/ctypes/__init__.py", line 369, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(RTLD_DEFAULT, magic_open): symbol not found

**Comment by sim0nx** [comment]
Hi,

You are missing a (libmagic) system library, please see #9  for details.
