### ISSUE TITLE
Error when importing eml_parser

### ISSUE THREAD

**Issue by bcalisch** [GOVCERT-LU/eml_parser#14]
Hello.  This is my first time making an issue, so be easy on me.  I have tried importing eml_parser on 3.6.1, 3.6.2, and 3.6.3 and when I import eml_parser I get an error.  I posted the error below.  Any help would be greatly appreciated. 

Traceback (most recent call last):
  File "getError.py", line 5, in <module>
    import eml_parser
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\eml_parser\__init__.py", line 8, in <module>
    from . import eml_parser
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\eml_parser\eml_parser.py", line 63, in <module>
    import magic
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\magic.py", line 23, in <module>
    _libraries['magic'] = _init()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\magic.py", line 20, in _init
    return ctypes.cdll.LoadLibrary(find_library('magic'))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\ctypes\__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
TypeError: LoadLibrary() argument 1 must be str, not None

**Comment by sim0nx** [comment]
Hi,

I must admit that I have never tried eml_parser on windows. My guess is that you don't have the "magic" library installed (in addition to the python lib).

See the windows dependencies on https://github.com/ahupp/python-magic  (not the library required for eml_parser but same windows deps).

Let me know if this works for you.

**Comment by Foxdelmar** [comment]
I have the same error. Windows 10, Python 3.6.3
I installed magic using: pip install libmagic

I found a few threads that discuss similar errors. For example https://github.com/pymedusa/Medusa/issues/1843
This and other threads refer to the following bug: http://bugs.python.org/issue29082 which exists for more then one year. But with my knowledge I can not find a solution to solve this issue.

Do you have any clue?

**Comment by sim0nx** [comment]
I'm sorry but I can't really help you with Windows problems here besides the link I posted earlier :-/
If you don't necessarily need mime parsing support, give it a try without the mime library.

**Comment by sal-git** [comment]
I submitted a pull request with the fix. It works on my machine now. 

Check if it is a windows machine and if it is, use libmagic

**Comment by sim0nx** [comment]
Unfortunately as noted in the PR #16 , that is not a valid fix.
You must either remove the file-magic python library or properly install libmagic DLL.

**Comment by alexander-gr** [comment]
I've just installed python-magic:
`pip install python-magic`
