### ISSUE TITLE
Dependancy error (ctypes) - TypeError: bad argument type for built-in operation

### ISSUE THREAD

**Issue by MehdiBela** [GOVCERT-LU/eml_parser#21]
Hello. I've been trying to use this package but I can't get it working because of an error in dependancy. I'm working with Python 3.6.1 on Windows 7. Below is full traceback. Let me know if I can provide additional info.

```
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:/Users/USER/Desktop/Antoine/GitHub/ChronoManager\Chronos\views\views.py", line 18, in index
    import eml_parser
  File "C:\Program Files (x86)\Python\lib\site-packages\eml_parser\__init__.py", line 8, in <module>
    from . import eml_parser
  File "C:\Program Files (x86)\Python\lib\site-packages\eml_parser\eml_parser.py", line 63, in <module>
    import magic
  File "C:\Program Files (x86)\Python\lib\site-packages\magic.py", line 23, in <module>
    _libraries['magic'] = _init()
  File "C:\Program Files (x86)\Python\lib\site-packages\magic.py", line 20, in _init
    return ctypes.cdll.LoadLibrary(find_library('magic'))
  File "C:\Program Files (x86)\Python\lib\ctypes\__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "C:\Program Files (x86)\Python\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
TypeError: bad argument type for built-in operation
```

**Comment by sim0nx** [comment]
Hi
Can you confirm that you have successfully installed the python module file-magic>=0.4.0 as well as the file magic DLL ?

**Comment by sim0nx** [comment]
The windows section at:
https://github.com/ahupp/python-magic

might help. Note: python-magic != file-magic, they share the same DLL though which is why I point you there.

**Comment by sim0nx** [comment]
You installed python-magic along with the DLL. python-magic and file-magic use the same module name which is why their installation is mutually exclusive.
In your case this was detected and magic usage was disabled. What this means is that mime-types are not resolved dynamically and as such are missing from the output.

To fix this, you would need to uninstall python-magic-bin, re-install file-magic, and only download / build the "file magic" DLL from the before mentioned URL.
