### ISSUE TITLE
encoding error on bounced messages

### ISSUE THREAD

**Issue by joaoreis81** [GOVCERT-LU/eml_parser#38]
In a bounced message I got:

The undelivered mail returned to sender with Content-Type: text/plain; charset=us-ascii
The attached message returned has Content-Type: text/plain; charset=iso-8859-1

eml_parser return the following error:
`Traceback (most recent call last):
  File "/home/joao/Projects/email-engine/eml_parser_test.py", line 18, in <module>
    parsed_eml = eml_parser.eml_parser.decode_email_b(message, include_raw_body=False, include_attachment_data=True)
  File "/home/joao/Projects/email-engine/venv/lib64/python3.7/site-packages/eml_parser/eml_parser.py", line 417, in decode_email_b
    return parse_email(msg, include_raw_body, include_attachment_data, pconf, parse_attachments=parse_attachments)
  File "/home/joao/Projects/email-engine/venv/lib64/python3.7/site-packages/eml_parser/eml_parser.py", line 893, in parse_email
    report_struc['attachment'] = traverse_multipart(msg, 0, include_attachment_data)
  File "/home/joao/Projects/email-engine/venv/lib64/python3.7/site-packages/eml_parser/eml_parser.py", line 206, in traverse_multipart
    attachments.update(traverse_multipart(part, counter, include_attachment_data))  # type: ignore
  File "/home/joao/Projects/email-engine/venv/lib64/python3.7/site-packages/eml_parser/eml_parser.py", line 203, in traverse_multipart
    prepare_multipart_part_attachment(msg, counter, include_attachment_data))  # type: ignore
  File "/home/joao/Projects/email-engine/venv/lib64/python3.7/site-packages/eml_parser/eml_parser.py", line 249, in prepare_multipart_part_attachment
    data = bytes(payload[0])
  File "/usr/lib64/python3.7/email/message.py", line 164, in __bytes__
    return self.as_bytes()
  File "/usr/lib64/python3.7/email/message.py", line 178, in as_bytes
    g.flatten(self, unixfrom=unixfrom)
  File "/usr/lib64/python3.7/email/generator.py", line 116, in flatten
    self._write(msg)
  File "/usr/lib64/python3.7/email/generator.py", line 195, in _write
    self._write_headers(msg)
  File "/usr/lib64/python3.7/email/generator.py", line 418, in _write_headers
    self._fp.write(self.policy.fold_binary(h, v))
  File "/usr/lib64/python3.7/email/policy.py", line 200, in fold_binary
    folded = self._fold(name, value, refold_binary=self.cte_type=='7bit')
  File "/usr/lib64/python3.7/email/policy.py", line 214, in _fold
    return self.header_factory(name, ''.join(lines)).fold(policy=self)
  File "/usr/lib64/python3.7/email/headerregistry.py", line 258, in fold
    return header.fold(policy=policy)
  File "/usr/lib64/python3.7/email/_header_value_parser.py", line 157, in fold
    return _refold_parse_tree(self, policy=policy)
  File "/usr/lib64/python3.7/email/_header_value_parser.py", line 2698, in _refold_parse_tree
    part.ew_combine_allowed, charset)
  File "/usr/lib64/python3.7/email/_header_value_parser.py", line 2785, in _fold_as_ew
    encoded_word = _ew.encode(to_encode_word, charset=encode_as)
  File "/usr/lib64/python3.7/email/_encoded_words.py", line 222, in encode
    bstring = string.encode('ascii', 'surrogateescape')
UnicodeEncodeError: 'ascii' codec can't encode characters in position 4-6: ordinal not in range(128)

Process finished with exit code 1`

An option to NOT parse attached messages would be great, or just change the encoding to open the attachment would work, I think.

I've attached the message too. 

Thanks in advance.
[amostra_eml.txt](https://github.com/GOVCERT-LU/eml_parser/files/3854731/amostra_eml.txt)

**Comment by sim0nx** [comment]
Thank for reporting this!
There is actually an option to skip parsing attachments:
parse_attachments = False

I have fixed this though to properly parse your message; thanks for including it :-)
