### ISSUE TITLE
'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by kinoute** [GOVCERT-LU/eml_parser#54]
Hello,

I'm getting this error on some EML files with the newest version of the library. 

With the old version 1.11.7, I don't have this problem.

### Python 3.8.7 / eml_parser 1.11.7

```shell
python3
Python 3.8.7 (default, Dec 30 2020, 10:13:09)
[Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import eml_parser
>>> parsed_eml = eml_parser.eml_parser.decode_email("1.eml", 
include_raw_body=True, include_attachment_data=False, parse_attachments=True)
>>> parsed_eml
{'body': [{'uri': ['....
```

### Python 3.8.7 / eml_parser 1.14.4

```shell
python3
Python 3.8.7 (default, Dec 30 2020, 10:13:09)
[Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import eml_parser
>>> parser = eml_parser.EmlParser(include_raw_body=True, include_attachment_data=False, parse_attachments=True)
>>> parsed_eml = parser.decode_email("1.eml")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/eml_parser/eml_parser.py", line 979, in decode_email
    return decode_email_b(eml_file=raw_email,
  File "/usr/local/lib/python3.8/site-packages/eml_parser/eml_parser.py", line 1040, in decode_email_b
    return ep.decode_email_bytes(eml_file)
  File "/usr/local/lib/python3.8/site-packages/eml_parser/eml_parser.py", line 192, in decode_email_bytes
    return self.parse_email()
  File "/usr/local/lib/python3.8/site-packages/eml_parser/eml_parser.py", line 315, in parse_email
    parsed_routing = eml_parser.routing.parserouting(received_line_flat)
  File "/usr/local/lib/python3.8/site-packages/eml_parser/routing.py", line 164, in parserouting
    out[item.strip()] = cleanline(reparseg.group(item.strip()))  # type: ignore
AttributeError: 'NoneType' object has no attribute 'group'
```

I sent an EML with this problem to George's email address.

Regards

**Comment by sim0nx** [comment]
Hi,

Thank you for your report! This has been fixed in the latest release.
