### ISSUE TITLE
Unable to parse via stdin

### ISSUE THREAD

**Issue by saveman71** [GOVCERT-LU/eml_parser#73]
```python
#!/usr/bin/env python

import sys
import datetime
import json
import eml_parser


def json_serial(obj):
  if isinstance(obj, datetime.datetime):
      serial = obj.isoformat()
      return serial


raw_email = sys.stdin.read()

ep = eml_parser.EmlParser()
parsed_eml = ep.decode_email_bytes(raw_email)

print(json.dumps(parsed_eml, default=json_serial))
```

I fixed my issue by opening the file with a filename given in parameter but thought you might want to know ;)

The stacktrace is:

```
Traceback (most recent call last):
  File "/home/test/./parse.py", line 18, in <module>
    parsed_eml = ep.decode_email_bytes(raw_email)
  File "/home/test/env/lib/python3.10/site-packages/eml_parser/eml_parser.py", line 210, in decode_email_bytes
    self.msg = email.message_from_bytes(_eml_file, policy=self.policy)
  File "/usr/lib/python3.10/email/__init__.py", line 46, in message_from_bytes
    return BytesParser(*args, **kws).parsebytes(s)
  File "/usr/lib/python3.10/email/parser.py", line 122, in parsebytes
    text = text.decode('ASCII', errors='surrogateescape')
AttributeError: 'str' object has no attribute 'decode'. Did you mean: 'encode'?
```

**Comment by sim0nx** [comment]
You are reading a str from stdin and trying to pass that to a method which expects a bytes object ;-)

**Comment by saveman71** [comment]
Ah I see thank you and sorry for the useless issue ;)

**Comment by sim0nx** [comment]
no problem :-)

**Comment by wangtaohe** [comment]
嗯   已经收到了 。。。
