### ISSUE TITLE
TypeError on load

### ISSUE THREAD

**Issue by zbalkan** [GOVCERT-LU/eml_parser#85]
# Summary

A `TypeError` is thrown during initialization.

# Test environment

It is easy to reproduce as it throws the error at the beginning.

```
OS: Windows 10
Python: 3.10.11
```

## requirements.txt

```ini
charset-normalizer==3.1.0
eml-parser==1.17.5
file-magic==0.4.1
publicsuffixlist==0.9.4
python-dateutil==2.8.2
six==1.16.0
```

## eml.py

```python
import datetime
import json
from typing import Any

import eml_parser


class EmlFile:
    content: dict

    def __init__(self, path: str) -> None:
        with open(path, 'rb') as fhdl:
            raw_email: bytes = fhdl.read()
            self.content = eml_parser.EmlParser().\
                decode_email_bytes(raw_email)

    @staticmethod
    def __json_serial(obj: Any) -> str | Any:
        if isinstance(obj, datetime.datetime):
            serial: str = obj.isoformat()
            return serial
        return obj

    def __str__(self) -> str:
        return json.dumps(self.content, default=EmlFile.__json_serial)
```

## main.py

```python
import logging
import os
import sys
from typing import Final

from eml import EmlFile

APPLICATION_NAME: Final[str] = 'TEST'


def get_root_dir() -> str:
    if getattr(sys, 'frozen', False):
        return os.path.dirname(sys.executable)
    elif __file__:
        return os.path.dirname(__file__)
    else:
        return './'


def main() -> None:
    path: str = "TEST.eml"
    eml = EmlFile(path=path)
    print('finished')


if __name__ == "__main__":
    try:
        logging.basicConfig(filename=os.path.join(get_root_dir(), f'{APPLICATION_NAME}.log'),
                            encoding='utf-8',
                            format='%(asctime)s %(message)s',
                            level=logging.DEBUG)

        excepthook = logging.error
        logging.info('Starting')
        main()
        logging.info('Exiting')
    except KeyboardInterrupt:
        print('Cancelled by user.')
        logging.error("Cancelled by user.")
        logging.info('Exiting')
        try:
            sys.exit(0)
        except SystemExit:
            os._exit(0)
    except Exception as ex:
        print('ERROR: ' + str(ex))
        logging.info('Exiting')
        try:
            sys.exit(1)
        except SystemExit:
            os._exit(1)
```

# Error Message
```
Exception has occurred: TypeError
argument of type 'NoneType' is not iterable
  File "<redacted>\eml-test\eml.py", line 5, in <module>
    import eml_parser
  File "<redacted>\eml-test\main.py", line 6, in <module>
    from eml import EmlFile
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by sim0nx** [comment]
Based on the provided information, I am unable to reproduce your error.
I tested it with the same python version as you noted.

Also based on the error you get I am not sure this is related to eml_parser at all.

**Comment by zbalkan** [comment]
According to he traceback, it is not the `eml_parser` but the `magic` dependency which creates the issue:

```
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "<REDACTED>\.vscode\extensions\ms-python.python-2023.6.1\pythonFiles\lib\python\debugpy\__main__.py", line 39, in <module>
    cli.main()
  File "<REDACTED>\.vscode\extensions\ms-python.python-2023.6.1\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 430, in main
    run()
  File "<REDACTED>\.vscode\extensions\ms-python.python-2023.6.1\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "<REDACTED>\.vscode\extensions\ms-python.python-2023.6.1\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "<REDACTED>\.vscode\extensions\ms-python.python-2023.6.1\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "<REDACTED>\.vscode\extensions\ms-python.python-2023.6.1\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "main.py", line 6, in <module>
    from eml import EmlFile
  File "<REDACTED>\repos\eml-test\eml.py", line 5, in <module>
    import eml_parser
  File "<REDACTED>\eml-test\.venv\lib\site-packages\eml_parser\__init__.py", line 6, in <module>
    from .parser import EmlParser
  File "<REDACTED>\eml-test\.venv\lib\site-packages\eml_parser\parser.py", line 70, in <module>
    import magic
  File "<REDACTED>\eml-test\.venv\lib\site-packages\magic.py", line 24, in <module>
    _libraries['magic'] = _init()
  File "<REDACTED>\eml-test\.venv\lib\site-packages\magic.py", line 21, in _init
    return ctypes.cdll.LoadLibrary(find_library('magic'))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\ctypes\__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\ctypes\__init__.py", line 364, in __init__
    if '/' in name or '\\' in name:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by zbalkan** [comment]
It looks like whether you use `pip install eml_parser[filemagic]` or `pip install eml_parser`, the result is the same. It works if you install `filemagic`package separately.

**Comment by sim0nx** [comment]
The result should not be the same as when you just install eml_parser, there will be no file-magic (unless it is already installed), and it should just work, except for mime-type detection.

With filemagic it works, because that is not the correct package and probably does not use the magic module name.

The correct module is called file-magic.

I am not using windows thus I can't really help you here; this is more a problem of how to correctly install file-magic on windows which does require the natice libmagic DLL which it can't find on your system.

As an alternative you can install python-magic manually instead, which should work as a drop-in replacement to file-magic (it exposes a file-magic compatibility interface).

Hope this helps
