### ISSUE TITLE
Email address with special characters

### ISSUE THREAD

**Issue by gdesmar** [GOVCERT-LU/eml_parser#86]
I was trying to debug a message and was able to trim it down to a very small an [shareable one](https://github.com/GOVCERT-LU/eml_parser/files/14336761/d5e19298510adcb4cb8c1346c826611fa44134150ff6433e174f2e4b145c9b08.zip). I think that the accent in the second email is partially the cause of the issue as if I remove it, it will be parsed correctly. At the same time, adding an empty line as the first line of the file also fixes the issue, so I'm pretty stumped. I was wondering if you had an idea on what could be the true cause of this issue.

```python
>>> import eml_parser
>>> parser = eml_parser.EmlParser(include_raw_body=True, include_attachment_data=True)
>>> parsed_eml = parser.decode_email_bytes(open("d5e19298510adcb4cb8c1346c826611fa44134150ff6433e174f2e4b145c9b08", "rb").read())
Traceback (most recent call last):
  File ".../site-packages/eml_parser/parser.py", line 829, in headeremail2list
    field = email.utils.getaddresses(self.msg.get_all(header, []))
  File ".../email/message.py", line 510, in get_all
    values.append(self.policy.header_fetch_parse(k, v))
  File ".../email/policy.py", line 163, in header_fetch_parse
    return self.header_factory(name, value)
  File ".../email/headerregistry.py", line 601, in __call__
    return self[name](name, value)
  File ".../email/headerregistry.py", line 196, in __new__
    cls.parse(value, kwds)
  File ".../email/headerregistry.py", line 343, in parse
    [Address(mb.display_name or '',
  File ".../email/headerregistry.py", line 344, in <listcomp>
    mb.local_part or '',
AttributeError: 'Group' object has no attribute 'local_part'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../site-packages/eml_parser/parser.py", line 214, in decode_email_bytes
    return self.parse_email()
  File ".../site-packages/eml_parser/parser.py", line 299, in parse_email
    headers_struc['to'] = self.headeremail2list('to')
  File ".../site-packages/eml_parser/parser.py", line 831, in headeremail2list
    field = email.utils.getaddresses(eml_parser.decode.workaround_bug_27257(self.msg, header))
  File ".../site-packages/eml_parser/decode.py", line 149, in workaround_bug_27257
    m = eml_parser.regexes.email_regex.findall(value)
TypeError: expected string or buffer
```

Thank you for your time!

**Comment by sim0nx** [comment]
Your provided sample does not seem to be valid. thunderbird for example displays "something", but not what is in your **to:** field.
If you change the **to** field to:
> To: To2 - Accentué Company1 <to2@c.com>

which still includes the accent, eml_parser happily parses it.

Could it be that your original EML is somehow broken ?

**Comment by gdesmar** [comment]
As you showed with your example, I think it may come from having a colon in the text before the email. Sadly I do not have access anymore to the real original email causing this issue to check how it got to this state. Maybe something else previously removed quotes that could help with the parsing (or corrupted it in another way). I will close this ticket and add some checks on my side to remove colons when that error triggers. Thank you very much for looking into it!
